package com.childmindr.chilmindrbackend.seeder

import com.childmindr.chilmindrbackend.model.Profile
import com.childmindr.chilmindrbackend.repository.ProfileRepository
import org.springframework.stereotype.Component
import java.util.*

@Component
class ProfileSeeder(private val profileRepository: ProfileRepository, private val childminderSeeder: ChildminderSeeder) {
    val childminders = childminderSeeder.seedChildminders().toList()

    fun seedProfiles(): MutableIterable<Profile>  {
        val profile1 = Profile(UUID.randomUUID(), "07709091138", false, true, bio = "<p>At Happy Hearts Childcare, every day is an adventure in learning and laughter! Our mission is to create a nurturing and stimulating environment where children can thrive emotionally, socially, and intellectually.</p><p>We offer high-quality care and education for children ages 6 weeks to 5 years old. Our curriculum is designed to meet the unique needs of each child, fostering growth and development in a safe and supportive setting.</p><p>We embrace diversity and celebrate the individuality of each child. Our curriculum balances structured learning activities with child-directed play, stimulating creativity, curiosity, and critical thinking skills.</p><p>Safety is our top priority. Our facility is equipped with secure entry systems, surveillance cameras, and rigorous safety protocols. Our staff undergoes extensive training to maintain the highest standards of safety and security.</p><p>We believe in building strong partnerships with families to support the holistic development of each child. Open communication and collaboration between parents and teachers are encouraged.</p><p>But what truly sets us apart is the warmth and love that permeates every aspect of our center. Our caring staff is passionate about making a difference in the lives of children, creating a nurturing environment where children feel safe, supported, and loved unconditionally.</p><p>If you're looking for a childcare provider who will treat your child like family, look no further than Happy Hearts Childcare. Come visit us today and see the difference that love and laughter can make in your child's life!</p>", childminderId = childminders[0].id)
        val profile2 = Profile(UUID.randomUUID(), "07981230171", true, false, bio = "<p>Discover the wonder of childhood at Tiny Sprouts Childcare, where every moment is filled with growth and joy! Our mission is to cultivate a nurturing and stimulating environment where young minds blossom and flourish.</p><p>We specialize in providing exceptional care and education for children ages 6 weeks to 5 years old. Our curriculum is thoughtfully crafted to meet the individual needs of each child, fostering a love for learning and exploration.</p><p>At Tiny Sprouts, we celebrate diversity and embrace the unique qualities of each child. Our curriculum integrates structured learning activities with playful exploration, encouraging creativity, curiosity, and problem-solving skills.</p><p>Your child's safety is our top priority. Our facility is equipped with secure entry systems, surveillance cameras, and stringent safety protocols. Our staff receives thorough training to ensure the highest standards of safety and security.</p><p>We believe in the power of partnerships between families and educators. We foster open communication and collaboration, creating a supportive community where every child can thrive.</p><p>What sets Tiny Sprouts apart is our commitment to creating a nurturing and loving environment. Our dedicated staff is passionate about making a positive impact on the lives of children, providing care that is both compassionate and enriching.</p><p>If you're seeking a childcare provider that values growth, joy, and individuality, look no further than Tiny Sprouts Childcare. Visit us today and witness the magic of childhood unfold!</p>", childminderId = childminders[1].id)
        return profileRepository.saveAll(listOf(profile1, profile2))
    }
}